# frozen_string_literal: true

class LocationPdf
  require "prawn"
  require "prawn/table"

  def initialize(location, reviews)
    @location = location
    @reviews  = reviews
    @doc      = Prawn::Document.new(page_size: "A4", margin: 36)
    build
  end

  def render
    @doc.render
  end

  private

  def build
    header
    meta_table
    features_section
    images_section
    reviews_section
    footer
  end

  def header
    @doc.text("OpenDoors", size: 18, style: :bold, color: "1D4ED8")
    @doc.move_down(8)
    @doc.text(@location.name.to_s, size: 24, style: :bold)
    @doc.text(full_address, size: 11, color: "555555")
    @doc.move_down(12)
    @doc.stroke_horizontal_rule
    @doc.move_down(12)
  end

  def meta_table
    rows = [
      ["City", @location.city],
      ["State", @location.state],
      ["Zip", @location.zip],
      ["Country", @location.country],
      ["Latitude", @location.latitude],
      ["Longitude", @location.longitude],
    ]
    @doc.table(rows, column_widths: [100, 400]) do
      row(0..-1).columns(0).font_style = :bold
      cells.padding = 6
      self.header = false
    end
    @doc.move_down(10)
  end

  def features_section
    return if @location.features.blank?

    @doc.text("Features", size: 16, style: :bold)
    @doc.move_down(6)
    bullets = @location.features.map { |f| "• #{f.feature}" }
    @doc.text(bullets.join("\n"), size: 11, leading: 2)
    @doc.move_down(10)
  end

  def images_section
    return unless @location.pictures.attached?

    @doc.text("Photos", size: 16, style: :bold)
    @doc.move_down(6)

    # Render up to 3 images side-by-side, 160px tall
    width = 160
    @location.pictures.select(&:variable?).first(3).each do |att|
      blob = att.blob
      # Download image bytes and feed into Prawn
      io = StringIO.new(blob.download)
      @doc.image(io, fit: [width, 160], position: :left)
      @doc.move_down(6)
    rescue => e
      @doc.text("Image failed to render (#{e.class})", size: 9, color: "999999")
    end

    @doc.move_down(10)
  end

  def reviews_section
    return if @reviews.blank?

    @doc.text("Recent Reviews", size: 16, style: :bold)
    @doc.move_down(6)

    @reviews.first(5).each do |r|
      @doc.text("by #{r.user&.email_address || "Anonymous"} — #{r.created_at.strftime("%b %d, %Y")}", size: 10, color: "555555")
      @doc.text(r.content.to_s, size: 11)
      @doc.move_down(8)
      @doc.stroke_horizontal_rule
      @doc.move_down(8)
    end
  end

  def footer
    @doc.move_down(12)
    @doc.stroke_horizontal_rule
    @doc.move_down(6)
    @doc.text("Generated by OpenDoors", size: 9, align: :right, color: "888888")
  end

  def full_address
    [@location.address, @location.city, @location.state, @location.zip, @location.country].compact_blank.join(", ")
  end
end
